version: "3.9"
services:
  fastapi-app:
    volumes:
      - ./logs/:./logs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
